Assemblr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('posts/', views.posts_index, name='index'),
    path('posts/my_posts/', views.my_posts, name='my_posts'),
    path('posts/<int:post_id>/', views.posts_detail, name='detail'),

    path('posts/create/', views.PostCreate.as_view(), name='posts_create'),
    path('posts/<int:pk>/update/', views.PostUpdate.as_view(), name='posts_update'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='posts_delete'),

    path('posts/<int:post_id>/add_message/', views.add_message, name='add_message'),

    path('messages/<int:pk>/update/', views.MessageUpdate.as_view(), name='messages_update'),
    path('messages/<int:pk>/delete/', views.MessageDelete.as_view(), name='messages_delete'),

    path('messages/<int:pk>/', views.MessageDetail.as_view(), name="message_detail"),
    path('accounts/signup/', views.signup, name='signup'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import date


PROGRAMS = (
    ('s', 'Software Engineer'),
    ('u', 'UX Design'),
)
COHORTS = (
    ('ATX', 'Austin'),
    ('DAL', 'Dallas'),
    ('LAN', 'Los Angeles'),
    ('SAN', 'San Diego'),
    ('DEN', 'Denver'),
)

SKILLS = (
    ('HTML', 'HTML'),
    ('CSS', 'CSS'),
    ('JS', 'JavaScript'),
    ('UX', 'UX Design'),
    ('PI', 'Project Ideas'),
)

# =========Student Model=========
class Student(models.Model):
    name = models.CharField(max_length=50)

    cohort = models.CharField(
        max_length=3,
        choices=COHORTS,
        default=COHORTS[0][0]
    )
    program = models.CharField(
        max_length=1,
        choices=PROGRAMS,
        default=PROGRAMS[0][0]
    )

    def __str__(self):
        return f"{self.name} - {self.get_cohort_display().upper()}"

    def get_absolute_url(self):
        return reverse('posts_detail', kwargs={'pk': self.id})




# ========= Post Model =========
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    skill = models.CharField(
        max_length=4,
        choices=SKILLS,
        default=SKILLS[0][0]
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'post_id': self.id})

    class Meta:
        ordering = ['-created_at']
    
# ========= Message Model =========
class Message(models.Model):
    comment = models.TextField(max_length=1000)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"message id = {self.id} on {self.created_at}"

    def get_absolute_url(self):
        return reverse('message_detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ['-created_at']

main_app/forms.py
from django.forms import ModelForm
from .models import Message, Student

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['comment']


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post, Student, Message
from .forms import MessageForm, StudentForm



# ========= CBV's ===================

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = '/posts/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    success_url = '/posts/'


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/posts/'


class MessageDetail(LoginRequiredMixin, DetailView):
    model = Message


class MessageUpdate(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ['comment']

    def get_success_url(self):
        return reverse('detail', kwargs={'post_id': self.object.post.id})


class MessageDelete(LoginRequiredMixin, DeleteView):
    model = Message
    
    def get_success_url(self):
        return reverse('detail', kwargs={'post_id': self.object.post.id})

# ========= Functions ===================

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def posts_index(request):
    posts = Post.objects.all()
    return render(request, 'posts/index.html', {'posts': posts})

@login_required
def my_posts(request):
    my_posts = Post.objects.filter(user=request.user)
    return render(request, 'posts/my_posts.html', {'my_posts' : my_posts})

@login_required
def posts_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    message_form = MessageForm()
    return render(request, 'posts/detail.html', {'post': post, 'message_form': message_form})

@login_required
def add_message(request, post_id):
    form = MessageForm(request.POST)
    if form.is_valid():
        new_message = form.save(commit=False)
        new_message.post_id = post_id
        new_message.user = request.user
        new_message.save()
    return redirect('detail', post_id=post_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assemblr</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Assemblr</a></li>
                    <li><img style="margin-left: 160px;" alt="Assemblr Logo" width="50" src={% static '/images/logo.png' %}></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'index' %}">All Posts</a></li>
                        <li><a href="{% url 'my_posts' %}">My Posts</a></li>
                        <li>Welcome Back <span style="color: red;">{{ user.username }}</span>!</li>
                        <li><a href="{% url 'logout' %}">Log Out</a></li>
                        {% else %}
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'login' %}">Log In</a></li>
                        {% endif %}
                        
                </ul>
            </div>
        </nav>
    </header>
<body>
<main>


<h4>About Us</h4>
<div class="row">
    <div class="col s6">
        <div class="carousel carousel-slider">
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students1.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students2.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students3.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students4.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students5.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students6.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students7.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students8.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students9.jpg' %}"></a>
            <a class="carousel-item" href="#one!"><img src="{% static '/images/students10.jpg' %}"></a>
        </div>
    </div>
    <div class="col s6"><span class="flow-text">
    <div class="card black">
    <div class="card-content white-text">
      <h6>Assemblr is an app that brings together UX Designers &amp; Sofware Engineers from General Assembly programs. Our goal is to connect students who are looking for help on a project or who simply want to lend a helping hand to a fellow GA student. If you need help on a project, simply create a post so others can respond.</h6>
      <h6>Assemblr also aims to help students beyond their experience at General Assembly. By providing access to a database of freelance job opportunities, Assemblr helps graduates obtain experience while they continue their job search.</h6>
      </span>
    </div>
    </div>
    </div>
</div>


<script>
M.AutoInit();
$('.carousel.carousel-slider').carousel({
    fullWidth: true
  });
setInterval(function(){
  $('.carousel').carousel('next');
}, 5000);
</script>
</main>

<footer class="page-footer">
    <div class="footer-copyright">© 2020 Python Pirates</div>
    <div class=""></div>
</footer>

</body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assemblr</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<header class="navbar-fixed">
    <nav>
    <div class="nav-wrapper">
        <ul>
            <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Assemblr</a></li>
            <li><img style="margin-left: 160px;" alt="Assemblr Logo" width="50" src={% static '/images/logo.png' %}></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'index' %}">All Posts</a></li>
            <li><a href="{% url 'my_posts' %}">My Posts</a></li>
            <li>Welcome Back <span style="color: red;">{{ user.username }}</span>!</li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
        </ul>
    </div>
    </nav>
</header>

<body>
    {% block content %}
    {% endblock %}
<script type="text/javascript" src="js/materialize.min.js"></script>
</body>

<footer class="page-footer">
    <div class="footer-copyright">© 2020 Python Pirates</div>
    <div class=""></div>
</footer>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="row" style="padding: 0; margin: 0; min-height: 100vh;">
    <div class="col s6 red" style="min-height: 100vh;">
    </br>
    </br>
    </br>
    </br>
    </br>
       <h1 style="color: white; font-size: 32px; padding: 20px;" class="flow-text">Network &amp; find freelance gigs to help you build your portfolio while you obtain hands-on experience.</h1>
        <button type="submit" style="align: center; background-color: black;" class="btn"><a href="{% url 'about' %}">Learn More</a></button>
    </div>

    <div class="col s6 white" style="min-height: 100vh;">
    </br>
    </br>
    </br>
    </br>
    </br>
<div class="container">
<h1>Sign Up</h1>

{% if error_message %}<p class="red-text">{{ error_message }}</p>{% endif %}

<form method="post" action="{% url 'signup' %}">
{% csrf_token %}

<p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username"></p>

<p><label for="id_password1">Password:</label> <input type="password" name="password1" autocomplete="new-password" required id="id_password1"> <span class="helptext"></span></p>

<p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" autocomplete="new-password" required id="id_password2"></p>

<input style="align: center;" type="submit" class="btn" value="signup">

</form>
</div>






    
    </div>

</div>

{% endblock %}

main_app/templates/main_app/message_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<main>
    <h1>Delete Message</h1>

    <h4>Are you sure you want to delete this Message?</h4>
  
    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes - Delete!" class="btn">
      <a style="color: blue" href="{% url 'detail' message.post.id %}">Cancel</a>
    </form>
</main>
{% endblock %}

main_app/templates/main_app/message_detail.html
{% extends 'base.html' %}
{% block content %}
<main>
<h4>Conversation</h4>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ message.title }}</span>
        <p>{{ message.created_at }}</p>
        <br>
        <br>
        <p>{{ message.content }}</p>
       
      </div>
      <div class="card-action">
        <a href="">Edit</a>
        <a href="">Delete</a>
      </div>
    </div>
</main>
    



{% endblock %}

main_app/templates/main_app/message_form.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Edit Your Message</h1>
  
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
  </main>
{% endblock %}

main_app/templates/main_app/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<main>
    <h1>Delete Post</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>
  
    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes - Delete!" class="btn">
      <a href="{% url 'detail' post.id %}">Cancel</a>
    </form>
</main>

{% endblock %}

main_app/templates/main_app/post_form.html
<!-- THIS IS A TEST TEMPLATE -->
{% extends 'base.html' %}
{% block content %}

<main>
{% if object %}
<h1>Edit <span class="teal-text">{{object.title}}</span></h1>
{% else %}
<h4>Add Post</h4>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
</main>

{% endblock %}

main_app/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}
<main>
<div class="container">
<h4>Post Details</h4>
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ post.title }}</span>
          <p>{{ post.created_at }}</p>
          <p style="color: teal">{{ post.user.username }}</p>
          <!-- <p>Keywords: {{ post.genre }}</p> -->
          <!-- Doesn't seem like we will have time to do the search functionality
          We can always come back and add it -->
          <br>
          <br>
          <p>{{ post.content }}</p>
        </div>
        {% if user.username == post.user.username %}
          <div class="card-action">
              <a style="color: black;" href="{% url 'posts_update' post.id %}"><i class="material-icons">edit</i></a>
              <a style="color: black;" href="{% url 'posts_delete' post.id %}"><i class="material-icons">delete</i></a>
          </div>
        {% endif %}
      </div>
    </div>

  <form action="{% url 'add_message' post.id %}" method="post">
          {% csrf_token %}
          {{ message_form.as_p }}
          <input type="submit" class="btn" value="Reply to This Post">
        </form>
      </div>
    </div>
    
    
    
    
    
  </div>
  
  {% for message in post.message_set.all %}
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        From <p style="color: teal">{{ message.user }}</p>
        <p>On {{ post.created_at }}</p>
        <!-- <p>Keywords: {{ post.skill }}</p> -->
        <!-- Doesn't seem like we will have time to do the search functionality
        We can always come back and add it -->
        <br>
        <br>
        <p class="flow-text">{{ message.comment }}</p>
      </div>
        {% if user.username == message.user.username %}
        <div class="card-action">
            <a style="color: black;" href="{% url 'posts_update' post.id %}"><i class="material-icons">edit</i></a>
            <a style="color: black;" href="{% url 'posts_delete' post.id %}"><i class="material-icons">delete</i></a>
        </div>
        {% endif %}
    </div>
  </div>
  {% endfor %}
</main>
{% endblock %}

main_app/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
<br>
<main>
<button type="submit" class="btn">
  <a href="{% url 'posts_create' %}">Create A New Post</a>
</button>
{% for post in posts %}
  <div class="card black darken-1">
    <a href="{% url 'detail' post.id %}">
    <div class="card-content white-text">
      <span class="card-title">{{ post.title }}</span>
      <p>{{ post.created_at }}</p>
      <p style="color: red;">Posted By {{ post.user.username }}</p>
    </div>
    </a>
{% if user.username == post.user.username %}
    <div class="card-action">
      <a style="color: white;" href="{% url 'posts_update' post.id %}"><i class="material-icons">edit</i></a>
      <a style="color: white;" href="{% url 'posts_delete' post.id %}"><i class="material-icons">delete</i></a>
    </div>
{% endif %}
  </div>
{% endfor %}
</main>
{% endblock %}

main_app/templates/posts/my_posts.html
{% extends 'base.html' %}
{% block content %}
<main>
<h4>My Posts</h4>

{% for post in my_posts %}
<div class="card black darken-1">
  <a href="{% url 'detail' post.id %}">
  <div class="card-content white-text">
    <span class="card-title">{{ post.title }}</span>
    <p>{{ post.created_at }}</p>
    <p style="color: red">Posted By {{ post.user.username }}</p>
  </div>
    </a>
  <div class="card-action">
    <a style="color: white;" href="{% url 'posts_update' post.id %}"><i class="material-icons">edit</i></a>
    <a style="color: white;" href="{% url 'posts_delete' post.id %}"><i class="material-icons">delete</i></a>
  </div>
</div>
  {% endfor %}
  <button type="submit" class="btn">
  <a href="{% url 'posts_create' %}">Create A New Post</a>
</button>
</main>






{% endblock %}